### ISSUE TITLE
https://berserkapi.kutaybekleric.com/ not working

### ISSUE THREAD

**Issue by Praveensenpai** [kutaui/BerserkAPI#1]
error: Cannot GET /

**Comment by kutaui** [comment]
In my end it is still working as intended, can you elaborate the steps you took.
This endpoint has all the characters:
https://berserkapi.kutaybekleric.com/characters

If you want to get one by one you'll need to add id starting from 0 up to 9. Example:
https://berserkapi.kutaybekleric.com/characters/1
